### ISSUE TITLE
Performance profiles are useless please delete

### ISSUE THREAD

**Issue by harrisonmoss** [TechnologyMan101/linux-mint-setup-script#2]
DELETE PLEASE Thanks! they are **USELESS** delete please Thanks!

**Comment by harrisonmoss** [comment]
![desktop](https://user-images.githubusercontent.com/52843844/92313919-2783a980-ef9f-11ea-880d-6f4c72b843b6.png)
so bad useless os. Don't be like ubuntu. Use lnux mint.

**Comment by TechnologyMan101** [comment]
Will release new version in a few minutes.

**Comment by harrisonmoss** [comment]
thanks! You are so good at bash.

**Comment by TechnologyMan101** [comment]
you're welcome
